//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.EzTravel.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkmemberrenewal
    {
        public int ID { get; set; }
        public int MemberRenewalID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public string ProductDescription { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double SubTotal { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
    }
}
